CREATE TABLE "SYSTEM"."MESSAGE"
(
    "ID"           NUMBER(15, 0) NOT NULL PRIMARY KEY ,
    "USER_ID"      NUMBER(15, 0) REFERENCES USERS (ID),
    "MESSAGE_DATE" TIMESTAMP(6),
    "TEXT"         VARCHAR2(255 CHAR)
)