CREATE TABLE "SYSTEM"."TASK"
(
    "ID"        NUMBER(10, 0) NOT NULL ENABLE,
    "STATUS"    VARCHAR2(255 BYTE),
    "DATE_FROM" TIMESTAMP(6),
    "DATE_TO"   TIMESTAMP(6),
    CONSTRAINT "TASK_PK" PRIMARY KEY ("ID")
);